import '../imports/util/simpl-schema-config';

// CARS
import '../imports/api/cars/cars';
import '../imports/api/cars/methods';
// ORDERS
import '../imports/api/orders/orders';
import '../imports/api/orders/methods';
// USER_FILES
import '../imports/api/userFiles/userFiles';
import '../imports/api/userFiles/methods';
// DOCUMENTS
import '../imports/api/documents/documents';
import '../imports/api/documents/methods';
// USERS
import '../imports/api/users/users';
import '../imports/api/users/methods';
// VALUATIONS
import '../imports/api/valuations/valuations';
import '../imports/api/valuations/methods';
// CLAIMS
import '../imports/api/claims/claims';
import '../imports/api/claims/methods';
// STATION_PROFILES
import '../imports/api/stationProfiles/stationProfiles';
import '../imports/api/stationProfiles/methods';
